-- Optional production scheduler for the balance-monitor Edge Function.
--
-- Requirements in Supabase Dashboard:
-- 1. Enable the `pg_cron` extension.
-- 2. Enable the `pg_net` extension.
-- 3. Store `project_url` and `balance_monitor_secret` in Supabase Vault.
--
-- This migration is intentionally commented out because projects differ in extension
-- permissions and secret-storage policy. Apply manually after confirming pg_cron/pg_net
-- are enabled in production.

-- SELECT cron.schedule(
--   'instead-balance-monitor-every-15-minutes',
--   '*/15 * * * *',
--   $$
--   SELECT net.http_post(
--     url := (select decrypted_secret from vault.decrypted_secrets where name = 'project_url') || '/functions/v1/balance-monitor',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-monitor-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'balance_monitor_secret')
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
